$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: .
command: python train_model.py --num_epochs 3 --input_dir ${{inputs.fowl_data}} --output_dir outputs 
environment: azureml:AzureML-pytorch-1.10-ubuntu18.04-py38-cuda11-gpu:35
compute: azureml:kinfeygpucompute
environment_variables:
  AZUREML_COMPUTE_USE_COMMON_RUNTIME: "false"
inputs:
  fowl_data:
     type: uri_folder
     path: azureml:fowl-data:1

experiment_name: pytorch-training-experiment