on:
  push:
    branches: [ master ]

name: AzureMLOpsTrain

jobs:
  setup-aml-and-train:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout MLOps Repository
      id: checkout_repository
      uses: actions/checkout@v2

    - name: Log in with Azure
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true 
          
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 

    - name: Azure CLI script - Prepare and run PyTorch Demo  Training on Azure ML
      uses: azure/CLI@v1
      with:
        azcliversion: 2.50.0
        inlineScript: |
          az extension add -n ml
          cd MLOps
          az ml compute create --file compute.yml --subscription ${{ secrets.AZURE_SUBSCRIPTION }} --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.AML_WORKSPACE }}
          az ml job create --file train.yml --subscription ${{ secrets.AZURE_SUBSCRIPTION }} --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.AML_WORKSPACE }}

