on:
  push:
    branches: [ master ]

name: AzureMLOpsTrain


permissions:
  id-token: write
  contents: read

jobs:
  setup-aml-and-train:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout MLOps Repository
      id: checkout_repository
      uses: actions/checkout@v2
        
    - name: Installing Az CLI Edge build 
      run: |
        cd ../..
        CWD="$(pwd)"
        python3 -m venv canary-venv
        . canary-venv/bin/activate
        echo "***********activated virual environment**********" 
        python3 -m pip install --upgrade pip
        echo "***************started installing cli edge build******************"
        pip3 install -q --upgrade --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge --no-cache-dir --upgrade-strategy=eager
        echo "***************installed cli Edge build*******************"    
        echo "$CWD/canary-venv/bin" >> $GITHUB_PATH
        az --version

    - name: Log in with Azure
      uses: azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

          
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 

    - name: Azure CLI script - Prepare and run PyTorch Demo  Training on Azure ML
      uses: azure/CLI@v1
      with:
        azcliversion: 2.50.0
        inlineScript: |
          az extension add -n ml
          cd MLOps
          az ml compute create --file compute.yml --subscription ${{ secrets.AZURE_SUBSCRIPTION }} --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.AML_WORKSPACE }}
          az ml job create --file train.yml --subscription ${{ secrets.AZURE_SUBSCRIPTION }} --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.AML_WORKSPACE }}

